@endpoint = https://dqxp2k6265.execute-api.ca-central-1.amazonaws.com/prod
GET {{endpoint}}/hello/
###

POST {{endpoint}}/reservations/
Content-Type: application/json

{
  "location": "Miami",
  "name": "Best location"
}
###
